import { useCallback, useEffect, useState, type ReactNode } from "react";
import { loadNotifications, markAllNotificationsRead, markNotificationRead, type WorkflowNotification } from "../api/client";
import type { IconName, PageKey } from "../types/navigation";
import type { WorkspaceSummary } from "../types/workspace";
import { Icon } from "./Icon";

type NavItem = { label: PageKey; icon: IconName; badge?: string };
const commonItems: NavItem[] = [
  { label: "Overview", icon: "grid" }, { label: "Time entries", icon: "clock" },
  { label: "Projects", icon: "folder" }, { label: "Reports", icon: "chart" },
];

function Sidebar({ activePage, onSelect, open, onClose, workspace, pendingApprovalCount }: { activePage: PageKey; onSelect: (page: PageKey) => void; open: boolean; onClose: () => void; workspace: WorkspaceSummary; pendingApprovalCount: number }) {
  const role = workspace.membership.role;
  const workspaceItems = role === "member" ? commonItems : [...commonItems, { label: "Approvals" as const, icon: "check" as const, ...(pendingApprovalCount > 0 ? { badge: String(pendingApprovalCount) } : {}) }];
  const manageItems: NavItem[] = role === "admin" ? [{ label: "Members", icon: "users" }, { label: "Settings", icon: "settings" }] : [];
  const renderItems = (items: NavItem[]) => items.map((item) => <button key={item.label} className={`nav-item ${activePage === item.label ? "nav-item--active" : ""}`} type="button" onClick={() => { onSelect(item.label); onClose(); }}><Icon name={item.icon} /><span>{item.label}</span>{item.badge && <b aria-label={`${item.badge} pending approvals`}>{item.badge}</b>}</button>);
  return <aside className={`sidebar ${open ? "sidebar--open" : ""}`}><div className="brand"><span className="brand-mark">T</span><strong>tempo<span>ledger</span></strong></div><button className="workspace-switcher" type="button"><span>{workspace.name.slice(0, 2).toUpperCase()}</span><div><strong>{workspace.name}</strong><small>{role} workspace</small></div><Icon name="chevron" size={15} /></button><label className="sidebar-search"><Icon name="search" size={18} /><input placeholder="Search..." /></label><nav aria-label="Main navigation"><p className="nav-label">WORKSPACE</p>{renderItems(workspaceItems)}{manageItems.length > 0 && <><div className="nav-divider" /><p className="nav-label">MANAGE</p>{renderItems(manageItems)}</>}</nav><div className="sidebar-footer"><button type="button"><Icon name="help" size={17} /> Help center</button><small>TempoLedger v1.0</small></div></aside>;
}

function Topbar({ onOpenSidebar, userEmail, workspaceId, accessToken, onNavigate }: { onOpenSidebar: () => void; userEmail: string; workspaceId: string; accessToken: string; onNavigate: (path: string) => void }) {
  const initials = userEmail.split("@")[0].split(/[._-]/).map((part) => part[0]).join("").slice(0, 2).toUpperCase();
  const [open, setOpen] = useState(false); const [notifications, setNotifications] = useState<WorkflowNotification[]>([]); const [unreadCount, setUnreadCount] = useState(0);
  const load = useCallback(async () => { try { const result = await loadNotifications(workspaceId, accessToken); setNotifications(result.notifications); setUnreadCount(result.unreadCount); } catch { /* Notifications stay non-blocking. */ } }, [accessToken, workspaceId]); useEffect(() => { void load(); const onFocus = () => void load(); window.addEventListener("focus", onFocus); const timer = window.setInterval(() => void load(), 60_000); return () => { window.removeEventListener("focus", onFocus); window.clearInterval(timer); }; }, [load]);
  const openNotification = async (item: WorkflowNotification) => { if (!item.readAt) { setNotifications((values) => values.map((value) => value.id === item.id ? { ...value, readAt: new Date().toISOString() } : value)); setUnreadCount((value) => Math.max(0, value - 1)); try { await markNotificationRead(workspaceId, item.id, accessToken); } catch { /* Navigation remains available if read-state sync fails. */ } } setOpen(false); onNavigate(item.href); };
  const markAll = async () => { await markAllNotificationsRead(workspaceId, accessToken); setNotifications((items) => items.map((item) => ({ ...item, readAt: item.readAt ?? new Date().toISOString() }))); setUnreadCount(0); };
  return <header className="topbar"><button className="mobile-menu" type="button" aria-label="Open navigation" onClick={onOpenSidebar}><Icon name="list" size={21} /></button><div className="topbar-actions"><button type="button" aria-label="Search"><Icon name="search" /></button><div className="notification-anchor"><button type="button" aria-label="Notifications" onClick={() => setOpen((value) => !value)}><Icon name="bell" />{unreadCount > 0 && <span className="notification-count">{unreadCount > 9 ? "9+" : unreadCount}</span>}</button>{open && <section className="notification-popover"><header><div><strong>Notifications</strong><span>{unreadCount} unread</span></div>{unreadCount > 0 && <button onClick={() => void markAll()}>Mark all read</button>}</header><div>{notifications.length === 0 ? <p className="notification-empty">No workflow notifications yet.</p> : notifications.map((item) => <button className={item.readAt ? "notification-item" : "notification-item notification-item--unread"} key={item.id} onClick={() => void openNotification(item)}><i /><span><strong>{item.title}</strong><small>{item.body}</small><time>{new Date(item.createdAt).toLocaleString()}</time></span></button>)}</div></section>}</div><button className="user-menu" type="button"><span>{initials}</span><strong>{userEmail}</strong><Icon name="chevron" size={13} /></button></div></header>;
}

function LogTimeModal({ onClose }: { onClose: () => void }) {
  return <div className="modal-backdrop" role="presentation" onClick={onClose}><section className="log-modal" role="dialog" aria-modal="true" aria-labelledby="log-title" onClick={(event) => event.stopPropagation()}><div className="modal-heading"><div><p className="section-kicker">NEW ENTRY</p><h2 id="log-title">Log time</h2></div><button className="bare-button" type="button" onClick={onClose} aria-label="Close dialog"><Icon name="close" size={18} /></button></div><label>Project<select defaultValue="Northstar redesign"><option>Northstar redesign</option><option>Cedar &amp; Co. website</option><option>Atlas product audit</option></select></label><label>Description<input defaultValue="Interface review" /></label><div className="modal-fields"><label>Date<input type="date" defaultValue="2025-03-12" /></label><label>Duration<input defaultValue="02:20" /></label></div><div className="modal-actions"><button className="subtle-button" type="button" onClick={onClose}>Cancel</button><button className="primary-button" type="button" onClick={onClose}>Save entry</button></div></section></div>;
}

export function DashboardLayout({ activePage, onSelectPage, onNavigate, accessToken, workspace, pendingApprovalCount, userEmail, children }: { activePage: PageKey; onSelectPage: (page: PageKey) => void; onNavigate: (path: string) => void; accessToken: string; workspace: WorkspaceSummary; pendingApprovalCount: number; userEmail: string; children: (onLogTime: () => void) => ReactNode }) {
  const [sidebarOpen, setSidebarOpen] = useState(false); const [logOpen, setLogOpen] = useState(false);
  return <div className="app-shell"><Sidebar activePage={activePage} onSelect={onSelectPage} open={sidebarOpen} onClose={() => setSidebarOpen(false)} workspace={workspace} pendingApprovalCount={pendingApprovalCount} />{sidebarOpen && <button className="sidebar-scrim" type="button" aria-label="Close navigation" onClick={() => setSidebarOpen(false)} />}<main className="main-content"><Topbar onOpenSidebar={() => setSidebarOpen(true)} userEmail={userEmail} workspaceId={workspace.id} accessToken={accessToken} onNavigate={onNavigate} /><div className="page-content">{children(() => setLogOpen(true))}</div></main>{logOpen && <LogTimeModal onClose={() => setLogOpen(false)} />}</div>;
}
